apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://34.21.210.4
  name: gke-cluster
contexts:
- context:
    cluster: gke-cluster
    user: jenkins
  name: default-context
current-context: default-context
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkpmaUtJTVRFakRlM3ljZ1JoWC02akp0eUVicUtIYkFlaXplNFdkR0xKWTgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjU4ZjU1OGM5LTNjNDUtNDIxZC1iNDU1LTMyMWI3YTczZTMwZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmplbmtpbnMifQ.tPTlebA-_IJzPobx_Zoi4n0p3pGWK0PwwSCf6W5_ar1tWk2b8GCmg6gLF5_nKrEGaQkp8pe6HEPxCwwvqcQ_j19YZ9VWj6JUx38jqiNTaTQTIq7SQhFhhju7lxPfrTMH5NVdVjAoHwkGPFRvOxoXlwWlTEgk74DN2uh-h8D03qoWFcJX7sscMT5hK565yEDKHW1gAl_nMbGz2kteQmQSg2D7q9f2q8jG1dRU_LLQjk7AictoE3REFVczNCZWBtxi84hH88j1e9KKeo28Ru022VeW-gXJb8KXX9JSC8yCeRFChKS3lLiro654TPMX1qauHhFMnqh5SN54iqANJEgEig
