apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://agentic-ai-control-plane:6443
  name: k8s-cluster
contexts:
- context:
    cluster: k8s-cluster
    user: jenkins
  name: default-context
current-context: default-context
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkJEeF92V3RqSWpicUpnRXlpZDRZR0htTnJ2SXM2NDRKRUZmeUlUOXBGWWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ0MmU0ODk2LWQ5ZDItNDJlYi05YjVmLTkwZGMyMTA3OTIzZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmplbmtpbnMifQ.DxxMerPU_oCxKvU5bpssuAxs79As3KTCXiO3IsbnuEfQZidl23n5kj-zTQCduPdsqx_HtdkuMHaYINwFmAyz9NaLjPvhnJfLzY6CYC-bMbJzV0T_RoFfZh-oDVXqWovYacicnJ1DGP6fePoa8I_MdhSBcIiLRGFhI660h59LmRaXVCLHEbs_vpvPL6P-UcHb9qZsNGqKHCtx81aGcSqsDyY0V7oiVoiJSw7x3At8ukaY_L64_dTJBiLOETlGK_6Ik6mge-dgE7wcGr7LGuxjj5gxFK1ZRg_Rz05TtUO4r6GQKSV7DMuTQL_A-CGI_AeutQhyAxJHgLYMxYToCIObYg
