apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: drift-api-keda-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drift-api
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  pollingInterval: 15
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local:80
      metricName: http_requests_per_second
      query: sum(rate(http_requests_total{app="drift-api"}[1m]))
      threshold: '20'
  - type: cpu
    metricType: Utilization
    metadata:
      value: "75"
